---
# Variable  NEXTCLOUD_APP_ADMINPASS in defaults/main.yml
# Variable  NEXTCLOUD_DB_ADMINPASS  in defaults/main.yml
# Variable  NEXTCLOUD_APP_USERNAME     in defaults/main.yml

- name: Print Variable
  debug:
    msg: "{{ item }}"
  with_items:
    - NEXTCLOUD_IP_APP: "{{ NEXTCLOUD_IP_APP }}"
    - NEXTCLOUD_IP_DB: "{{ NEXTCLOUD_IP_DB }}"
    - NEXTCLOUD_IP_NGINX: "{{ NEXTCLOUD_IP_NGINX }}"
    - NEXTCLOUD_IP_SUBNET: "{{ NEXTCLOUD_IP_SUBNET }}"
    - NEXTCLOUD_APP_USERNAME: "{{ NEXTCLOUD_APP_USERNAME }}"
    - NEXTCLOUD_APP_ADMINPASS: "{{ NEXTCLOUD_APP_ADMINPASS }}"
    - NEXTCLOUD_DB_ADMINPASS: "{{ NEXTCLOUD_DB_ADMINPASS }}"

- name: Create Network Nextcloud
  docker_network:
    name: network_nextcloud
    ipam_config:
      - subnet: "{{ NEXTCLOUD_IP_SUBNET }}"
        
- name: Create Volume Nextcloud
  docker_volume:
    name: "{{ item }}"
  with_items:
    - volume_nextcloud_db
    - volume_nextcloud_app

- name: Create Container Mariadb for Nextcloud
  docker_container:
    name: nextcloud_db
    image: mariadb:latest
    state: started
    restart_policy: always
    env:
      MYSQL_ROOT_PASSWORD: "{{ NEXTCLOUD_DB_ADMINPASS }}"
      MYSQL_DATABASE: nextcloud_db
    volumes: 
      - volume_nextcloud_db:/var/lib/mysql
      - volume_nextcloud_db:/etc/mysql/conf.d
    networks:
      - name: network_nextcloud
        ipv4_address: "{{ NEXTCLOUD_IP_DB }}"
        aliases:
          - nextcloud_db

- name: Create Container Nextcloud
  docker_container:
    name: nextcloud_app
    image: nextcloud:25.0.3-apache
    state: started
    restart_policy: always
    env:
      NEXTCLOUD_ADMIN_USER: "{{ NEXTCLOUD_APP_USERNAME }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ NEXTCLOUD_APP_ADMINPASS }}"
      MYSQL_DATABASE: nextcloud_db
      MYSQL_USER: root
      MYSQL_PASSWORD: "{{ NEXTCLOUD_DB_ADMINPASS }}"
      MYSQL_HOST: nextcloud_db
    volumes: 
      - volume_nextcloud_app:/var/www/html
    networks:
      - name: network_nextcloud
        ipv4_address: "{{ NEXTCLOUD_IP_APP }}"
        aliases:
          - nextcloud_app
      - name: network_nginx
        ipv4_address: "{{ NEXTCLOUD_IP_NGINX }}"
        aliases:
          - nextcloud_app
    links:
      - "nextcloud_db:nextcloud_db"

